language: node_js
node_js:
  - "stable"
dist: focal

before_install:
  - rvm install 3.1.0  
  - rvm use 3.1.0 --default
  - ruby --version
  - gem update --system  
  - gem install bundler
  - gem install faraday -v 1.10.0
  - gem install faraday-net_http

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: build
  on:
    branch: main