language: node_js
node_js:
  - "stable"
dist: focal

before_install:
  - gem install bundler
  - gem install faraday -v 1.10.0

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: build
  on:
    branch: main