language: node_js
node_js:
  - "stable"
dist: focal

before_install:
  - rvm install 2.7.6  
  - rvm use 2.7.6 --default
  - ruby --version
  - gem update --system  
  - gem install bundler
  - gem install faraday -v 1.10.0

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: build
  on:
    branch: main