language: node_js
node_js:
  - "stable"
dist: focal
before_script:
  - npm install
script:
  - npm run build

before_deploy:
  - cp -r build public

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: build
  on:
    branch: main